export const EDIT_OPTIONS = [
  {
    value: "rename",
    label: "Rename Block",
  },
  {
    value: "delete",
    label: "Delete Block",
  },
];

export const OPERATIONS = [
  {
    value: "addition",
    label: "( + ) Add",
  },
  {
    value: "subtraction",
    label: "( - ) Subtract",
  },
  {
    value: "division",
    label: "( / ) Divide",
  },
  {
    value: "multiplication",
    label: "( X ) Multiply",
  },
];

export const PARAMETER_LIST_DATA = [
  {
    section: "Property Details",
    parameters: [
      {
        value: "bathrooms",
        label: "Bathrooms",
        format: "number",
        functionality: () => {},
      },
      {
        value: "bedrooms",
        label: "Bedrooms",
        format: "number",
        functionality: () => {},
      },
      {
        value: "deckArea",
        label: "Deck Area",
        format: "size",
        functionality: () => {},
      },
      {
        value: "roomsCount",
        label: "Room Count",
        format: "number",
        functionality: () => {},
      },
      {
        value: "squareFeet",
        label: "Square Feet",
        format: "size",
        functionality: () => {},
      },
      {
        value: "stories",
        label: "Stories",
        format: "number",
        functionality: () => {},
      },
      {
        value: "unitsCount",
        label: "Unit Count",
        format: "number",
        functionality: () => {},
      },
      {
        value: "lotSquareFeet",
        label: "Lot Square Feet",
        format: "size",
        functionality: () => {},
      },
    ],
  },
  {
    section: "Financial Valuation",
    parameters: [
      {
        value: "pricePerSquareFoot",
        label: "Price Per Square Foot",
        format: "USD",
        functionality: () => {},
      },
      {
        value: "priorSaleAmount",
        label: "Prior Sale Amount",
        format: "USD",
        functionality: () => {},
      },
      {
        value: "assessedImprovementValue",
        label: "Assessed Improvement Value",
        format: "USD",
        functionality: () => {},
      },
      {
        value: "assessedLandValue",
        label: "Assessed Land Value",
        format: "USD",
        functionality: () => {},
      },
      {
        value: "assessedValue",
        label: "Assessed Value",
        format: "USD",
        functionality: () => {},
      },
      {
        value: "estimatedValue",
        label: "Estimated Value",
        format: "USD",
        functionality: () => {},
      },
      {
        value: "lastSaleAmount",
        label: "Last Sale Amount",
        format: "USD",
        functionality: () => {},
      },
    ],
  },
  {
    section: "Market Data",
    parameters: [
      {
        value: "suggestedRent",
        label: "Suggested Rent",
        format: "USD",
        functionality: () => {},
      },
      {
        value: "rentAmount",
        label: "Rent Amount",
        format: "USD",
        functionality: () => {},
      },
      {
        value: "medianIncome",
        label: "Median Income",
        format: "USD",
        functionality: () => {},
      },
      {
        value: "mlsListingPrice",
        label: "MLS Listing Price",
        format: "USD",
        functionality: () => {},
      },
    ],
  },
  {
    section: "Financial Status",
    parameters: [
      {
        value: "openMortgageBalance",
        label: "Open Mortgage Balance",
        format: "USD",
        functionality: () => {},
      },
      {
        value: "equityPercent",
        label: "Equity Percent",
        format: "percent",
        functionality: () => {},
      },
      {
        value: "estimatedEquity",
        label: "Estimated Equity",
        format: "USD",
        functionality: () => {},
      },
      {
        value: "yearsOwned",
        label: "Years Owned",
        format: "number",
        functionality: () => {},
      },
    ],
  },
];

export const PARAMS = [
  {
    id: "1", 
    section: "Property Details",
    value: "bathrooms",
    label: "Bathrooms",
    format: "number",
    input: 0,
    operator: "",
    visible: true,
  },
  {
    id: "2",
    section: "Property Details",
    value: "bedrooms",
    label: "Bedrooms",
    format: "number",
    input: 0,
    operator: "",
    visible: true,
  },
  {
    id: "3", 
    section: "Property Details",
    value: "deckArea",
    label: "Deck Area",
    format: "size",
    input: 0,
    operator: "",
    visible: true,
  },
  {
    id: "4",
    section: "Property Details",
    value: "roomsCount",
    label: "Room Count",
    format: "number",
    input: 0,
    operator: "",
    visible: true,
  },
  {
    id: "5",
    section: "Property Details",
    value: "squareFeet",
    label: "Square Feet",
    format: "size",
    input: 0,
    operator: "",
    visible: true,
  },
  {
    id: "6",
    section: "Property Details",
    value: "stories",
    label: "Stories",
    format: "number",
    input: 0,
    operator: "",
    visible: true,
  },
  {
    id: "7",
    section: "Property Details",
    value: "unitsCount",
    label: "Unit Count",
    format: "number",
    input: 0,
    operator: "",
    visible: true,
  },
  {
    id: "8",
    section: "Property Details",
    value: "lotSquareFeet",
    label: "Lot Square Feet",
    format: "size",
    input: 0,
    operator: "",
    visible: true,
  },
  {
    id: "9", 
    section: "Financial Valuation",
    value: "pricePerSquareFoot",
    label: "Price Per Square Foot",
    format: "USD",
    input: 0,
    operator: "",
    visible: true,
  },
  {
    id: "10",
    section: "Financial Valuation",
    value: "priorSaleAmount",
    label: "Prior Sale Amount",
    format: "USD",
    input: 0,
    operator: "",
    visible: true,
  },
  {
    id: "11",
    section: "Financial Valuation",
    value: "assessedImprovementValue",
    label: "Assessed Improvement Value",
    format: "USD",
    input: 0,
    operator: "",
    visible: true,
  },
  {
    id: "12",
    section: "Financial Valuation",
    value: "assessedLandValue",
    label: "Assessed Land Value",
    format: "USD",
    input: 0,
    operator: "",
    visible: true,
  },
  {
    id: "13",
    section: "Financial Valuation",
    value: "assessedValue",
    label: "Assessed Value",
    format: "USD",
    input: 0,
    operator: "",
    visible: true,
  },
  {
    id: "14",
    section: "Financial Valuation",
    value: "estimatedValue",
    label: "Estimated Value",
    format: "USD",
    input: 0,
    operator: "",
    visible: true,
  },
  {
    id: "15",
    section: "Financial Valuation",
    value: "lastSaleAmount",
    label: "Last Sale Amount",
    format: "USD",
    input: 0,
    operator: "",
    visible: true,
  },
  {
    id: "16",
    section: "Market Data",
    value: "suggestedRent",
    label: "Suggested Rent",
    format: "USD",
    input: 0,
    operator: "",
    visible: true,
  },
  {
    id: "17",
    section: "Market Data",
    value: "rentAmount",
    label: "Rent Amount",
    format: "USD",
    input: 0,
    operator: "",
    visible: true,
  },
  {
    id: "18",
    section: "Market Data",
    value: "medianIncome",
    label: "Median Income",
    format: "USD",
    input: 0,
    operator: "",
    visible: true,
  },
  {
    id: "19",
    section: "Market Data",
    value: "mlsListingPrice",
    label: "MLS Listing Price",
    format: "USD",
    input: 0,
    operator: "",
    visible: true,
  },
  {
    id: "20",
    section: "Financial Status",
    value: "openMortgageBalance",
    label: "Open Mortgage Balance",
    format: "USD",
    input: 0,
    operator: "",
    visible: true,
  },
  {
    id: "21",
    section: "Financial Status",
    value: "equityPercent",
    label: "Equity Percent",
    format: "percent",
    input: 0,
    operator: "",
    visible: true,
  },
  {
    id: "22",
    section: "Financial Status",
    value: "estimatedEquity",
    label: "Estimated Equity",
    format: "USD",
    input: 0,
    operator: "",
    visible: true,
  },
  {
    id: "23",
    section: "Financial Status",
    value: "yearsOwned",
    label: "Years Owned",
    format: "number",
    input: 0,
    operator: "",
    visible: true,
  },
]

export const SECTION_HEADERS = [
  "Property Details",
  "Financial Valuation",
  "Market Data",
  "Financial Status",
];